import numpy as np
print("numpy array creation")
a = np.array([[1,2,3],[4,5,6]], dtype = 'float')
print(a)
print('array created using passed tuple')
b = np.array((1,2,3))
print(b)
print ("An array initialized with all zeros:\n")
c = np.zeros((3,4))
print(c)
print("an array initialized will all 6's. mArray type is complex")
d = np.full((3,3),6,dtype='complex')
print(d)
print("a random array")
e=np.random.random((2,2))
print(e)
print("a sequential array with steps of 5 ")
f = np.arange(0,30,5)
print(f) 
print("a sequential array with 10 values between 0 and 5")
g=np.linspace(0,5,10)
print(g)